# Generated by Django 3.0.5 on 2020-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200617_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Prices'),
        ),
    ]
