# Generated by Django 3.0.5 on 2020-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200617_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(to='shop.Prices'),
        ),
    ]
