# Generated by Django 3.0.5 on 2020-06-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200618_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ManyToManyField(to='shop.Prices'),
        ),
    ]
