# Generated by Django 3.0.5 on 2020-07-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200701_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='varients',
            name='qty',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
