# Generated by Django 3.0.5 on 2020-07-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20200701_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varients', to='shop.Product'),
        ),
    ]
