# Generated by Django 3.0.5 on 2020-07-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20200704_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
