# Generated by Django 3.0.8 on 2020-07-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20200707_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varients',
            name='price',
        ),
        migrations.AddField(
            model_name='varients',
            name='price_measure',
            field=models.CharField(default='rs', help_text='rs, $, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='varients',
            name='price_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
