# Generated by Django 3.0.8 on 2020-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20200707_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='quantity_measure',
            field=models.CharField(default='gms', help_text='gms, kg, etc.', max_length=50, null=True),
        ),
    ]
