# Generated by Django 3.0.5 on 2020-06-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
