# Generated by Django 3.0.5 on 2020-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200614_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_five',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_four',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_two',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(to='shop.Publication'),
        ),
    ]
