# Generated by Django 3.0.5 on 2020-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200617_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(blank=True, to='shop.Prices'),
        ),
    ]
