# Generated by Django 3.0.5 on 2020-06-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200630_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varients',
            old_name='title',
            new_name='p_name',
        ),
    ]
