# Generated by Django 3.0.5 on 2020-06-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200630_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='varients',
            name='product',
        ),
        migrations.RemoveField(
            model_name='varients',
            name='qty',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='Varients',
        ),
    ]
