# Generated by Django 3.0.5 on 2020-07-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200630_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Varients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='varient',
            field=models.CharField(choices=[('None', 'None'), ('Quantity', 'Quantity')], default='None', max_length=10),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.AddField(
            model_name='varients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='varients',
            name='qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Quantity'),
        ),
    ]
