# Generated by Django 3.0.5 on 2020-07-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200701_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varients',
            old_name='gms',
            new_name='quantity',
        ),
    ]
