# Generated by Django 3.0.5 on 2020-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20200704_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='slier',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
