# Generated by Django 3.0.8 on 2020-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20200705_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varients',
            name='quantity',
        ),
        migrations.AddField(
            model_name='varients',
            name='quantity_measure',
            field=models.CharField(default=None, help_text='gms, kg, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='varients',
            name='quantity_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
