# Generated by Django 3.0.8 on 2020-07-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20200707_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varients',
            old_name='price_number',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='varients',
            name='price_measure',
        ),
    ]
