# Generated by Django 3.0.5 on 2020-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20200707_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='quantity_number',
            field=models.CharField(default='', max_length=70),
        ),
    ]
