# Generated by Django 3.0.8 on 2020-07-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20200713_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
