# Generated by Django 3.0.5 on 2020-07-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
